workspace:
  base: /go
  path: src/github.com/appleboy/drone-discord

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    environment:
      TAGS: netgo
    secrets: [ webhook_id, webhook_token ]
    commands:
      - make vet
      - make lint
      - make test-vendor
      - make misspell-check
      - make test
      - make coverage
      - make build
      # build binary for docker image
      - make static_build
    when:
      event: [ push, tag, pull_request ]

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    when:
      event: [ push, pull_request ]
      status: [ success ]

  release:
    image: appleboy/golang-testing
    pull: true
    environment:
      TAGS: netgo
    commands:
      - make release
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ 'latest' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch: [ master ]

  github:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets:
      - source: webhook_prod_id
        target: webhook_id
      - source: webhook_prod_token
        target: webhook_token
    when:
      status: [ success, failure ]

  facebook:
    image: appleboy/drone-facebook
    pull: true
    to: 1234973386524610
    secrets: [ fb_page_token, fb_verify_token ]
    when:
      status: [ changed, failure ]
